ake:
  host: ymlhost
  port: ymlport
  protokol: ymlprot
  konfig:
    # parametry połączenia
    imie: jan
    nazwisko: kowalski
    haslo: haslo uzytkownika
  role:
  - uzytkownik
  - administrator
  parametry:
  - nazwa: parametr1
    wartosc: wartosc1
  - nazwa: parametr2
    wartosc: wartosc2
  - wartosc: wartosc3
    nazwa: parametr3
  - wartosc: wartosc5
    nazwa: parametr5

ake2:
  wartosc1: ake2wartosc1yml
  wartosc2: ake2wartosc2yml

# actuator
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  # dla plugina com.gorylenko.gradle-git-properties
  info:
    git:
      mode: full
