ake:
  host: qq2host
  port: qq2port
  protokol: qq2prot
  konfig:
    # parametry połączenia
    imie: jan
    nazwisko: qqwalski
    haslo: haslo uzytkownika
  role:
  - uzytkownik
  - administrator
  parametry:
  - nazwa: parametr1
    wartosc: wartosc1
  - nazwa: parametr2
    wartosc: wartosc2
  - wartosc: wartosc3
    nazwa: parametr3
  - wartosc: wartosc4
    nazwa: parametr4

# actuator
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  # dla plugina com.gorylenko.gradle-git-properties
  info:
    git:
      mode: full
